Experiment 10: Data Analysis and Visualization

Question 1. Create a NumPy array and find the sum of all elements.

In [4]:
import numpy as np
arr = np.array([23, 98, 12, 65, 18, 22])
print("Array:", arr)
print("Sum of all elements:", np.sum(arr))

Array: [23 98 12 65 18 22]
Sum of all elements: 238


Question 2. Create a (3, 3) NumPy array. Find:
Sum of each row, Sum of each column, 2nd maximum element in the array

In [5]:
matrix = np.array([
    [23, 12, 4],
    [54, 6, 67],
    [3, 34, 22],
])

row_sums = np.sum(matrix, axis=1)
column_sums = np.sum(matrix, axis=0)
second_max = np.unique(matrix.flatten())[-2]

print("3x3 Matrix:", matrix)
print("Row sums:", row_sums)
print("Column sums:", column_sums)
print("Second maximum element:", second_max)

3x3 Matrix: [[23 12  4]
 [54  6 67]
 [ 3 34 22]]
Row sums: [ 39 127  59]
Column sums: [80 52 93]
Second maximum element: 54


Question 3. Perform matrix multiplication of any two n x n matrices.

In [8]:
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1],
])

product = matrix_a @ matrix_b
print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)
print("Matrix A x Matrix B:\n", product)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix A x Matrix B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Question 4. Write a Pandas program to get the powers of array values element-wise.

In [12]:
import pandas as pd
base_values = pd.Series([0, 1, 2, 3, 4], name="base")
power_values = pd.Series([1, 2, 3, 2, 1], name="power")
powered_values = base_values.pow(power_values)
print("Base values:\n", base_values)
print("Power values:\n", power_values)
print("Element-wise powers:\n", powered_values)

Base values:
 0    0
1    1
2    2
3    3
4    4
Name: base, dtype: int64
Power values:
 0    1
1    2
2    3
3    2
4    1
Name: power, dtype: int64
Element-wise powers:
 0    0
1    1
2    8
3    9
4    4
dtype: int64


Question 5. Write a Pandas program to get the first 3 rows of the given DataFrame.
Sample data:
exam_data = {'name': [...], 'score': [...], 'attempts': [...], 'qualify': [...]}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [15]:
exam_data = {
    "Name": ["Ananya", "Priya", "Aarti", "Divya", "Rohit", "Vijay", "Deepak", "Anil"],
    "Score": [12.5, 9, 16.5, np.nan, 9, 20, np.nan, 19],
    "Attempts": [1, 3, 2, 3, 2, 3, 1, 1],
    "Qualify": ["Yes", "No", "Yes", "No", "No", "Yes", "Yes", "No"],
}
labels = ["a", "b", "c", "d", "e", "f", "g", "h"]
exam = pd.DataFrame(exam_data, index=labels)
print("Complete DataFrame:\n", exam)
print("First three rows:\n", exam.head(3))

Complete DataFrame:
      Name  Score  Attempts Qualify
a  Ananya   12.5         1     Yes
b   Priya    9.0         3      No
c   Aarti   16.5         2     Yes
d   Divya    NaN         3      No
e   Rohit    9.0         2      No
f   Vijay   20.0         3     Yes
g  Deepak    NaN         1     Yes
h    Anil   19.0         1      No
First three rows:
      Name  Score  Attempts Qualify
a  Ananya   12.5         1     Yes
b   Priya    9.0         3      No
c   Aarti   16.5         2     Yes


Question 6. Write a Pandas program to find and replace missing values in the DataFrame.

In [17]:
filled_df = exam.copy()
filled_df["Score"] = filled_df["Score"].fillna(filled_df["Score"].mean())
print("DataFrame after replacing missing score values:\n", filled_df)

DataFrame after replacing missing score values:
      Name      Score  Attempts Qualify
a  Ananya  12.500000         1     Yes
b   Priya   9.000000         3      No
c   Aarti  16.500000         2     Yes
d   Divya  14.333333         3      No
e   Rohit   9.000000         2      No
f   Vijay  20.000000         3     Yes
g  Deepak  14.333333         1     Yes
h    Anil  19.000000         1      No


Question 7. Create a program to demonstrate different visual forms using Matplotlib.

In [18]:
import matplotlib.pyplot as plt

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
sales = [200, 150, 80, 190, 210, 100]
expenses = [160, 100, 100, 180, 130, 100]
categories = ["Rent", "Raw Materials", "Salary", "Miscellaneous"]
share = [25, 35, 30, 10]
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

axes[0, 0].plot(months, sales, marker="o", color="teal")
axes[0, 0].set_title("Line Chart: Monthly Sales")
axes[0, 0].set_ylabel("Sales")
axes[0, 0].grid(True, linestyle="--", alpha=0.5)

axes[0, 1].bar(months, expenses, color="orange")
axes[0, 1].set_title("Bar Chart: Monthly Expenses")
axes[0, 1].set_ylabel("Expenses")

axes[1, 0].scatter(sales, expenses, color="crimson")
axes[1, 0].set_title("Scatter Plot: Sales vs Expenses")
axes[1, 0].set_xlabel("Sales")
axes[1, 0].set_ylabel("Expenses")

axes[1, 1].pie(share, labels=categories, autopct="%1.1f%%", startangle=90)
axes[1, 1].set_title("Pie Chart: Expense Distribution")

plt.tight_layout()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'